site_name: quantide
repo_url: https://github.com/zillionare/quantide
repo_name: quantide

nav:
  - home: index.md
  - init-wizard: init-wizard.md

theme:
  name: material
  language: en

plugins:
  - search:
      lang: en
