site_name: pyqmt
repo_url: https://github.com/zillionare/pyqmt
repo_name: pyqmt

nav:
  - home: index.md
  - init-wizard: init-wizard.md

theme:
  name: material
  language: en

plugins:
  - search:
      lang: en
