[tox]
isolated_build = true
envlist = py313, lint

[gh-actions]
python =
    3.13: py313

[testenv:lint]
allowlist_externals = poetry
setenv =
    POETRY_VIRTUALENVS_CREATE = false
deps =
    poetry
commands_pre =
    poetry install --with dev,doc,test --no-interaction
commands =
    poetry run ruff check quantide
    poetry run ruff format --check quantide tests
    poetry run mypy -m quantide --exclude ^tests
    poetry build
    poetry run mkdocs build
    poetry run twine check dist/*

[testenv]
allowlist_externals = poetry
passenv = *
setenv =
    PYTHONPATH = {toxinidir}
    PYTHONWARNINGS = ignore
    POETRY_VIRTUALENVS_CREATE = false
deps =
    poetry
commands_pre =
    poetry install --with test --no-interaction
commands =
    poetry run pytest -s --cov=quantide --cov-append --cov-report=xml --cov-report term-missing tests
