[tox]
isolated_build = true
envlist = py313, lint

[gh-actions]
python =
    3.13: py313

[testenv:lint]
extras =
    dev
    doc
deps =
    poetry
commands =
    poetry run isort pyqmt
    poetry run black pyqmt tests
    poetry run flake8 pyqmt
    poetry run mypy -m pyqmt --exclude ^tests
    poetry build
    poetry run mkdocs build
    poetry run twine check dist/*

[testenv]
passenv = *
setenv =
    PYTHONPATH = {toxinidir}
    PYTHONWARNINGS = ignore
deps =
    poetry
extras =
    test
commands =
    poetry run pytest -s --cov=pyqmt --cov-append --cov-report=xml --cov-report term-missing tests
